update Search Page
zim89/happy-tails-mantine pull request #47
Opened 2024-02-12 08:19 UTC by zim89

add hook useDeviseSize
add CatalogProductList on Search Page
fixed offsets for scrollIntoView
fixed siblings for Pagination

ПРОБЛЕМА:
нужно сделать сброс страницы в пагинаторе на 1 при сбросе\изменении строки поиска

2024-02-12 13:14 UTC, SalOne22 commented
Можно добавить вот такой useEffect:
```
useEffect(() => {
  const params = new URLSearchParams(searchParams);
  if (params.has('page')) setPage(Number(params.get('page')!));
}, [searchParams]);
```

2024-02-13 11:59 UTC, SalOne22 requested changes
Есть конфликты с main

2024-02-13 17:00 UTC, zim89 commented
я обновлю мейн, подправлю код и потом снова закину

2024-02-15 12:39 UTC, zim89 commented
не принимай пр. проблема обнуления пагинатора не работает

2024-02-15 16:30 UTC, SalOne22 commented
Уже можно чекать?

2024-02-15 16:31 UTC, zim89 commented
можно

2024-02-15 16:38 UTC, SalOne22 approved these changes

2024-02-15 16:38 UTC, merged