Auth redux
zim89/happy-tails-mantine pull request #82
Opened 2024-03-07 10:51 UTC by zim89

2024-03-07 12:38 UTC, SalOne22 approved these changes
Потестирую когда домой прийду, или с телефона если смержишь

2024-03-07 18:33 UTC, SalOne22 requested changes
404 ответ на логине это так должно быть?

2024-03-08 05:26 UTC, zim89 commented
с логином все в порядке. возможно проблема из-за того, что некоторые переменные в .env нужно переименовать:
NEXT_PUBLIC_KEYCLOAK_AUTH_URL=
NEXT_PUBLIC_KEYCLOAK_CLIENT_ID=

2024-03-08 10:38 UTC, SalOne22 commented
> с логином все в порядке. возможно проблема из-за того, что некоторые переменные в .env нужно переименовать: NEXT_PUBLIC_KEYCLOAK_AUTH_URL= NEXT_PUBLIC_KEYCLOAK_CLIENT_ID=

Все равно не находит, пишет ошибку CORS, может надо проверять на деплое?

2024-03-08 11:02 UTC, zim89 commented
даже не знаю ... я вторую неделю с этим пытаюсь разобраться. при этом делал логаут вне редакса - результат такой же. писал Саше ... мол возможно это связано с бэком ... но пока не было фидбека. можем задеплоить ... на работу всего приложения пока не повлияет

2024-03-08 11:11 UTC, SalOne22 approved these changes
Ок, тогда проверю на деплое

2024-03-10 08:40 UTC, merged